# Generated by Django 4.0.3 on 2022-03-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myworkspace.role')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('project_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('username', models.CharField(max_length=20)),
                ('survey_id', models.IntegerField(default=0)),
                ('survey_url', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myworkspace.user')),
            ],
        ),
    ]
