# Generated by Django 4.0.3 on 2022-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
        migrations.AlterField(
            model_name='project',
            name='survey_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
